# Generated by Django 4.2.4 on 2023-11-17 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='edate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ تصحیح'),
        ),
    ]
